server:
  port: 8043
  servlet:
    encoding:
      force: true

spring:
  profiles:
#    active: db-maria
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: create # 개발 서버에서만 사용
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/bnook #로컬테스트
#    url: jdbc:mariadb://docker-compose-db-1:3306/bnook #mariadb 컨테이너명
#    username: root
#    password: root

    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/bnook
      user-name: sa
#      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true


