server:
  port: 8043
  servlet:
    encoding:
      force: true

spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true


